### PR TITLE
Initial Commit

### PR DESCRIPTION
**Pull request by Apply55gx**

### CODE REVIEW

**Comment by Apply55gx** [comment]
Könntest du einen eigenen Branch machen? Vielen Dank.

**Comment by queckezz** [comment]
Merged into branch `benjamin`. If you can, remove the license since the code you wrote is not copyrighted by yourself but by the concern.

**Comment by Apply55gx** [comment]
I created a pull request without the license.

**Comment by queckezz** [comment]
I gave you write permissions. In the future you can push directly without a PR

**Comment by Apply55gx** [comment]
Ok Thanks.
I'm a bit confused about the two readmes in my branch. Are they different?

**Comment by queckezz** [comment]
Hmm they are both the same. Merge issue. You can delete one if you want

**Pull request closed without merging**
